---
title: "Confined and Costly Data Dictionary"
date: "3/31/2021"
output: pdf_document
---

## adm_pop_change_comms.csv

`states` : State name  

`year`: Year  

`total.admissions`: Total admissions  

`total.violation.admissions`: Admissions for violations (probation and parole violations)   

`technical.violations.admissions`: Admissions for technical violations (technical probation and technical parole violations)   

`total.admissions.pct`: Change in total admissions from previous year   

`total.violation.admissions.pct`: Change in violation admissions from previous year    

`technical.violations.admissions.pct`: Change in technical violation admissions from previous year    

`total.population`: Total population  

`total.violation.population`: Population of violators (probation and parole violators)    

`technical.violations.population`: Population of technical violators (technical probation and technnical parole violators)     

`total.population.pct`: Change in total population from previous year     

`total.violation.population.pct`: Change in violation population from previous year   

`technical.violations.population.pct`:  Change in technical violation population from previous year  
